# Generated by Django 2.1.3 on 2019-01-13 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='金额')),
                ('type', models.IntegerField(default=0, verbose_name='支付状态')),
                ('riqi', models.DateField(verbose_name='日期')),
                ('shijianduan', models.CharField(default='', max_length=100, verbose_name='时间段')),
                ('chance', models.CharField(default='', max_length=10, verbose_name='场次')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': '订单详情',
            },
        ),
        migrations.CreateModel(
            name='Dongzuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='动作名称')),
                ('img', models.ImageField(default='', upload_to='', verbose_name='动作图片')),
            ],
            options={
                'verbose_name_plural': '动作',
            },
        ),
        migrations.CreateModel(
            name='Dongzuo_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke_time', models.CharField(max_length=40, verbose_name='课时')),
                ('shi_time', models.CharField(max_length=40, verbose_name='时长')),
                ('rank', models.CharField(max_length=40, verbose_name='难度等级')),
                ('produce', models.CharField(max_length=400, verbose_name='介绍')),
                ('people', models.CharField(max_length=400, verbose_name='人群')),
                ('video_name', models.CharField(max_length=40, verbose_name='视频名称')),
                ('name', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Dongzuo', verbose_name='动作名称')),
            ],
            options={
                'verbose_name_plural': '动作详情',
            },
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=20)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.TextField(max_length=200, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='所属区域')),
                ('username', models.CharField(default='', max_length=30, verbose_name='场馆名称')),
                ('img', models.ImageField(default='', upload_to='img/', verbose_name='场馆图片')),
                ('place', models.CharField(default='', max_length=50, verbose_name='地点')),
                ('distance', models.CharField(default='', max_length=30, verbose_name='距离')),
                ('assess', models.IntegerField(choices=[(1, '一星'), (2, '二星'), (3, '三星'), (4, '四星'), (5, '五星')], default=1)),
            ],
            options={
                'verbose_name': '场馆',
                'verbose_name_plural': '场馆',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('times', models.IntegerField(default=0)),
                ('con', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default='', max_length=20, verbose_name='服务')),
                ('tese', models.CharField(default='', max_length=20, verbose_name='场馆特色')),
                ('phnumber', models.CharField(default='', max_length=200, verbose_name='联系电话')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Place', verbose_name='场馆id')),
            ],
            options={
                'verbose_name_plural': '场馆详情',
            },
        ),
        migrations.CreateModel(
            name='Xuanke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riqi', models.DateField(verbose_name='有限日期')),
                ('shijianduan', models.CharField(max_length=100, verbose_name='时间段')),
                ('didian', models.CharField(max_length=100, verbose_name='房间')),
                ('neirong', models.CharField(max_length=100, verbose_name='授课内容')),
                ('chance', models.CharField(default='', max_length=10, verbose_name='场次')),
                ('price', models.CharField(max_length=100, verbose_name='金额')),
                ('renshu', models.IntegerField(verbose_name='人数')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Place')),
            ],
            options={
                'verbose_name_plural': '选课',
            },
        ),
        migrations.AddField(
            model_name='pinglun',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Place', verbose_name='评价场馆'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Place', verbose_name='场馆名称'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='xuke_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yujiaxm.Xuanke', verbose_name='选课id'),
        ),
    ]
